In [1]:
import pandas as pd
import numpy as np
import random
import mathplotlib.python as plt
import s

In [5]:
df=pd.read_excel('C:\\Users\\syamk\\Desktop\\5th sem\\Data science\\project\\fds_proj.xlsx')

In [6]:
df.head()

Unnamed: 0      locationmet otherpersons weather  temperature  currenttime  \
0           0  No Urgent Place        Alone   Sunny           55           11   
1           1  No Urgent Place    Friend(s)   Sunny           80            9   
2           2  No Urgent Place    Friend(s)   Sunny           80           12   
3           3  No Urgent Place    Friend(s)   Sunny           80           14   
4           4  No Urgent Place    Friend(s)   Sunny           80           13   

                  coupon expiration  gender  age  ...  occupation  income Bar  \
0        Restaurant(<20)         1d  Female   21  ...  Unemployed   40812   0   
1           Coffee House         2h  Female   21  ...  Unemployed   44198   0   
2  Carry out & Take away         2h  Female   21  ...  Unemployed   39978   0   
3           Coffee House         2h  Female   21  ...  Unemployed   48630   0   
4           Coffee House         1d  Female   21  ...  Unemployed   48583   0   

  CoffeeHouse  CarryAway  RestaurantLessThan20  Restaurant20To50  timein5  \
0           0          3                     7                38        1   
1           0          3                     5                35        1   
2           0          3                     7                50        1   
3           0          3                     5                27        1   
4           0          3                     7                29        1   

   timein15  timein25  
0         0         0  
1         0         0  
2         1         0  
3         1         0  
4         1         0  

[5 rows x 23 columns]

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12684 entries, 0 to 12683
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype 
---  ------                --------------  ----- 
 0   Unnamed: 0            12684 non-null  int64 
 1   locationmet           12684 non-null  object
 2   otherpersons          12684 non-null  object
 3   weather               12684 non-null  object
 4   temperature           12684 non-null  int64 
 5   currenttime           12684 non-null  int64 
 6   coupon                12684 non-null  object
 7   expiration            12684 non-null  object
 8   gender                12684 non-null  object
 9   age                   12684 non-null  int64 
 10  maritalStatus         12684 non-null  object
 11  has_children          12684 non-null  int64 
 12  education             12684 non-null  object
 13  occupation            12684 non-null  object
 14  income                12684 non-null  int64 
 15  Bar                   12684 non-null

In [8]:
df['RestaurantLessThan20'].unique()

array([ 7,  5,  4,  3,  1, 19, 16, 11, 12,  9, 13, 10, 20, 15, 18, 14,  8,
        0, 17], dtype=int64)

In [9]:
for i in range(0,len(df['RestaurantLessThan20'])):
    if df['RestaurantLessThan20'][i]==np.NaN:
        df['RestaurantLessThan20'][i]=0 
    else: 
        s=df['RestaurantLessThan20'][i]
        if s=="less1":
            df['RestaurantLessThan20'][i]=1
        elif s=="1~3":
            df['RestaurantLessThan20'][i]=3
        elif s=="never":
            df['RestaurantLessThan20'][i]=0
        elif s=="4~8":
            r=random.choice([4,5,7])
            df['RestaurantLessThan20'][i]=r
        elif s=="gt8":
            r=random.randint(8,20)
            df['RestaurantLessThan20'][i]=r 

In [10]:
df['RestaurantLessThan20']=df['RestaurantLessThan20'].fillna(0)

In [11]:
print(df['RestaurantLessThan20'])

0        7
1        5
2        7
3        5
4        7
        ..
12679    7
12680    5
12681    4
12682    7
12683    5
Name: RestaurantLessThan20, Length: 12684, dtype: int64


In [12]:
for i in range(0,len(df['Restaurant20To50'])):
    if df['Restaurant20To50'][i]==np.NaN:
         continue
    else: 
        s=df['Restaurant20To50'][i]
        r=random.randint(20,50)
        df['Restaurant20To50'][i]=r

<ipython-input-12-0113be84dbdd>:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Restaurant20To50'][i]=r


In [13]:
df['Restaurant20To50'].unique

<bound method Series.unique of 0        42
1        25
2        44
3        27
4        45
         ..
12679    29
12680    41
12681    23
12682    44
12683    27
Name: Restaurant20To50, Length: 12684, dtype: int64>

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12684 entries, 0 to 12683
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype 
---  ------                --------------  ----- 
 0   Unnamed: 0            12684 non-null  int64 
 1   locationmet           12684 non-null  object
 2   otherpersons          12684 non-null  object
 3   weather               12684 non-null  object
 4   temperature           12684 non-null  int64 
 5   currenttime           12684 non-null  int64 
 6   coupon                12684 non-null  object
 7   expiration            12684 non-null  object
 8   gender                12684 non-null  object
 9   age                   12684 non-null  int64 
 10  maritalStatus         12684 non-null  object
 11  has_children          12684 non-null  int64 
 12  education             12684 non-null  object
 13  occupation            12684 non-null  object
 14  income                12684 non-null  int64 
 15  Bar                   12684 non-null

In [15]:
df['age'].value_counts()

21    2653
26    2559
31    2039
36    1319
41    1093
46     686
60     184
58     182
56     174
59     166
57     165
51     161
53     159
52     157
55     154
54     146
50     140
18     134
20     113
16     109
19      96
17      95
Name: age, dtype: int64

In [16]:
for i in range(0,len(df['age'])):
        if df['age'][i]=="50plus":
            r=random.randint(50,60)
            df['age'][i]=r
        elif df['age'][i]=="below21":
            r= random.randint(16,20)
            df['age'][i]=r

In [17]:
df['age'].value_counts()

21    2653
26    2559
31    2039
36    1319
41    1093
46     686
60     184
58     182
56     174
59     166
57     165
51     161
53     159
52     157
55     154
54     146
50     140
18     134
20     113
16     109
19      96
17      95
Name: age, dtype: int64

In [18]:
df['Bar'].unique()

array([ 0,  1,  3, 13, 16, 17, 18,  8, 20, 12, 14,  9, 10, 19,  2,  4,  7,
        5, 11, 15], dtype=int64)

In [19]:
for i in range(0,len(df['Bar'])):
    if df['Bar'][i]==np.NaN:
        df['Bar'][i]=0 
    else: 
        s=df['Bar'][i]
        if s=="less1":
            df['Bar'][i]=1
        elif s=="1~3":
            df['Bar'][i]=3
        elif s=="never":
            df['Bar'][i]=0
        elif s=="4~8":
            r=random.choice([4,5,7])
            df['Bar'][i]=r
        elif s=="gt8":
            r=random.randint(8,20)
            df['Bar'][i]=r 

In [20]:
df['Bar'].unique()

array([ 0,  1,  3, 13, 16, 17, 18,  8, 20, 12, 14,  9, 10, 19,  2,  4,  7,
        5, 11, 15], dtype=int64)

In [21]:
k=df['Bar'].astype(float)
k.describe()

count    12684.000000
mean         1.721460
std          2.750713
min          0.000000
25%          0.000000
50%          1.000000
75%          3.000000
max         20.000000
Name: Bar, dtype: float64

In [22]:
df['Bar']=df['Bar'].fillna(2)

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12684 entries, 0 to 12683
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype 
---  ------                --------------  ----- 
 0   Unnamed: 0            12684 non-null  int64 
 1   locationmet           12684 non-null  object
 2   otherpersons          12684 non-null  object
 3   weather               12684 non-null  object
 4   temperature           12684 non-null  int64 
 5   currenttime           12684 non-null  int64 
 6   coupon                12684 non-null  object
 7   expiration            12684 non-null  object
 8   gender                12684 non-null  object
 9   age                   12684 non-null  int64 
 10  maritalStatus         12684 non-null  object
 11  has_children          12684 non-null  int64 
 12  education             12684 non-null  object
 13  occupation            12684 non-null  object
 14  income                12684 non-null  int64 
 15  Bar                   12684 non-null

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12684 entries, 0 to 12683
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype 
---  ------                --------------  ----- 
 0   Unnamed: 0            12684 non-null  int64 
 1   locationmet           12684 non-null  object
 2   otherpersons          12684 non-null  object
 3   weather               12684 non-null  object
 4   temperature           12684 non-null  int64 
 5   currenttime           12684 non-null  int64 
 6   coupon                12684 non-null  object
 7   expiration            12684 non-null  object
 8   gender                12684 non-null  object
 9   age                   12684 non-null  int64 
 10  maritalStatus         12684 non-null  object
 11  has_children          12684 non-null  int64 
 12  education             12684 non-null  object
 13  occupation            12684 non-null  object
 14  income                12684 non-null  int64 
 15  Bar                   12684 non-null

In [25]:
df['CarryAway'].value_counts()

3     4823
1     1856
4     1452
5     1416
7     1390
0      153
10     145
12     136
13     135
8      129
11     127
17     123
14     122
19     119
16     117
15     114
20     112
9      112
18     103
Name: CarryAway, dtype: int64

In [26]:
for i in range(0,len(df['CarryAway'])):
    if df['CarryAway'][i]==np.NaN:
        df['CarryAway'][i]=0 
    else: 
        s=df['CarryAway'][i]
        if s=="less1":
            df['CarryAway'][i]=1
        elif s=="1~3":
            df['CarryAway'][i]=3
        elif s=="never":
            df['CarryAway'][i]=0
        elif s=="4~8":
            r=random.choice([4,5,7])
            df['CarryAway'][i]=r
        elif s=="gt8":
            r=random.randint(8,20)
            df['CarryAway'][i]=r 

In [27]:
df['CarryAway'].unique()

array([ 3,  5,  7,  4, 19, 18, 15, 17,  8, 13, 16, 12, 10, 14,  9, 11, 20,
        1,  0], dtype=int64)

In [28]:
df['CarryAway']=df['CarryAway'].fillna(3)

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12684 entries, 0 to 12683
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype 
---  ------                --------------  ----- 
 0   Unnamed: 0            12684 non-null  int64 
 1   locationmet           12684 non-null  object
 2   otherpersons          12684 non-null  object
 3   weather               12684 non-null  object
 4   temperature           12684 non-null  int64 
 5   currenttime           12684 non-null  int64 
 6   coupon                12684 non-null  object
 7   expiration            12684 non-null  object
 8   gender                12684 non-null  object
 9   age                   12684 non-null  int64 
 10  maritalStatus         12684 non-null  object
 11  has_children          12684 non-null  int64 
 12  education             12684 non-null  object
 13  occupation            12684 non-null  object
 14  income                12684 non-null  int64 
 15  Bar                   12684 non-null

In [30]:
for i in range(0,len(df['CoffeeHouse'])):
    if df['CoffeeHouse'][i]==np.NaN:
        df['CoffeeHouse'][i]=0 
    else: 
        s=df['CoffeeHouse'][i]
        if s=="less1":
            df['CoffeeHouse'][i]=1
        elif s=="1~3":
            df['CoffeeHouse'][i]=3
        elif s=="never":
            df['CoffeeHouse'][i]=0
        elif s=="4~8":
            r=random.choice([4,5,7])
            df['CoffeeHouse'][i]=r
        elif s=="gt8":
            r=random.randint(8,20)
            df['CoffeeHouse'][i]=r

In [31]:
  df['CoffeeHouse']= df['CoffeeHouse'].fillna(0)

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12684 entries, 0 to 12683
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype 
---  ------                --------------  ----- 
 0   Unnamed: 0            12684 non-null  int64 
 1   locationmet           12684 non-null  object
 2   otherpersons          12684 non-null  object
 3   weather               12684 non-null  object
 4   temperature           12684 non-null  int64 
 5   currenttime           12684 non-null  int64 
 6   coupon                12684 non-null  object
 7   expiration            12684 non-null  object
 8   gender                12684 non-null  object
 9   age                   12684 non-null  int64 
 10  maritalStatus         12684 non-null  object
 11  has_children          12684 non-null  int64 
 12  education             12684 non-null  object
 13  occupation            12684 non-null  object
 14  income                12684 non-null  int64 
 15  Bar                   12684 non-null

In [33]:
df['income'].unique()

array([40812, 44198, 39978, ..., 86396, 77755, 82076], dtype=int64)

In [34]:
for i in range(0,len(df['income'])):
    s=df['income'][i]
    if s=="$37500 - $49999":
        r=random.randint(37500,49999)
        df['income'][i]=r
    elif s=="$62500 - $74999":
        r=random.randint(62500,74999)
        df['income'][i]=r
    elif s=="$12500 - $24999":
        r=random.randint(12500,24999)
        df['income'][i]=r
    elif s=='$75000 - $87499':
        r=random.randint(75000,87499)
        df['income'][i]=r
    elif s=='$50000 - $62499':
        r= random.randint(50000,62499)
        df['income'][i]=r
    elif s=='$25000 - $37499':
        r=random.randint(25000,37499)
        df['income'][i]=r
    elif s=='$100000 or More':
        r= random.randint(100000,110000)
        df['income'][i]=r
    elif s=='$87500 - $99999':
        r= random.randint(87500,99999)
        df['income'][i]=r
    else:
        r= random.randint(10000,12499)
        df['income'][i]=r
    

<ipython-input-34-1d977936526e>:29: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['income'][i]=r


In [35]:
for i in range(0,len(df['currenttime'])):
    df['currenttime'][i]=random.randint(9,21)

<ipython-input-35-32b04643678a>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['currenttime'][i]=random.randint(9,21)


In [36]:
df['currenttime'].value_counts()

11    1025
12    1007
14     997
13     991
15     983
20     975
10     974
16     972
17     967
21     964
9      958
19     938
18     933
Name: currenttime, dtype: int64

In [37]:
df.to_excel("C:\\Users\\vigne\\Desktop\\fds_proj.xlsx") 

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\vigne\\Desktop\\fds_proj.xlsx'